{% set name = "xaitk-saliency" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xaitk_saliency-{{ version }}.tar.gz
  sha256: 7cfb6affeb8bd3fde3fc10f3c635f65bd9f913729efdcc9398a8ce1ccd29d09a

build:
  skip: true  # [py>=400 or py2k]
  entry_points:
    - sal-on-coco-dets = xaitk_saliency.utils.bin.sal_on_coco_dets:sal_on_coco_dets
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy <1.25,>=1.22  # [py>=38 and py<39]
    - numpy <1.26,>=1.22  # [py>=39 and py<312]
    - numpy <2.0,>=1.26  # [py>=312]
    - scikit-image >=0.18.1  # [py>=38 and py<311]
    - scikit-image >=0.20  # [py>=311 and py<312]
    - scikit-image >=0.22  # [py>=312]
    - scikit-learn <1.4,>=1.2  # [py>=38 and py<312]
    - scikit-learn >=1.4  # [py>=312]
    - smqtk-classifier >=0.17.0
    - smqtk-core >=0.18.0
    - smqtk-descriptors >=0.16.0
    - smqtk-detection >=0.19.0
    - scipy <1.11.1  # [py>=38 and py<39]
    - scipy >=1.9  # [py>=39]
    - click >=8.0.3

test:
  imports:
    - xaitk_saliency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/XAITK/xaitk-saliency
  summary: Visual saliency map generation interfaces and baseline implementations for explainable AI.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - bjrichardwebster
    - barry-ravichandran
